version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.9.0.397
    steps:
      - checkout
      - restore_cache:
          key: timbre-json-appender-{{ checksum "deps.edn" }}
      - run: ./bin/kaocha
      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: timbre-json-appender-{{ checksum "deps.edn" }}
